# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-22 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(editable=False)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='autor',
            field=models.CharField(default='admin', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='poster',
            field=models.ImageField(null=True, upload_to='posters_post/'),
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='', editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='post',
            name='state',
            field=models.CharField(choices=[('b', 'Borrador'), ('p', 'Publicado')], default='b', max_length=1),
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(to='posts.Category'),
        ),
    ]
