# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-25 21:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20161125_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='poster',
        ),
    ]
