# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-05 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_remove_post_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='colorCss',
            field=models.CharField(default='', max_length=50),
        ),
    ]
