# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-05 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_post_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='colorCss',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
