# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-08 00:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_post_colorcss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='colorCss',
            field=models.CharField(blank=True, default='', editable=False, max_length=50),
        ),
    ]
